server:
  port: 8081
  http2:
    enabled: true
# grpc config
grpc:
  server:
    port: 9090
    security:
      enabled: true
      trustCertCollection: classpath:certs/ca.crt
      certificateChain: classpath:certs/server.crt
      privateKey: classpath:certs/server.key
      clientAuth: REQUIRE
spring:
  application:
    name: mail-service
  # kafka config
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      value-serializer: org.apache.kafka.common.serialization.StringSerializer # Serializer for the log message value (JSON string)
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
  # database config
#  datasource:
#    url: jdbc:postgresql://localhost:5432/pos_db
#    username: admin
#    password: root
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#      show_sql: true

# Outlook SMTP config
  mail:
    host: smtp.office365.com
    port: 587
    username: ${MAIL_USER}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000


# logging
logging:
  level:
    root: INFO
  # custom property
  kafka:
    bootstrap-servers: 192.168.240.52:9093,192.168.240.34:9093,192.168.245.118:9093
    topic: logs-topic
    username: log-producer
    password: log-producer@2025
    #security mTLS
    ssl-truststore-location: ./security/client.truststore.jks
    ssl-truststore-password: password
    ssl-keystore-location: ./security/client.keystore.jks
    ssl-keystore-password: password




